##################################===PROJECT===############################################
"""Guess Number: Randomly generate a number unknown to the user. The user needs to
guess what that number is. If the user's guess is wrong, the program should return some
sort of indication as to how wrong (e.g. the number is too high or too low). If the user
guesses correctly, a positive indication should appear. Write functions to check if the user
input is an actual number, to see the difference between the inputted number and the
randomly generated numbers, and to then compare the numbers."""
##################################===PREREQUISITES===############################################
# install pyttsx3 for TEXT TO SPEECH
# imported random to get a random number
# use of ascii characters
##################################===CREATIVITY===############################################
# ascii characters
# text to speech
# difficulty level mechanism according to the player
# comparison between Guessed number and the Number Generated by The Program.
# (eg. Too High, Too Low, High, Low)

from random import randint
import pyttsx3

text_speech= pyttsx3.init()

game= """
 ██████╗ ██╗   ██╗███████╗███████╗███████╗    ███╗   ██╗██╗   ██╗███╗   ███╗██████╗ ███████╗██████╗ 
██╔════╝ ██║   ██║██╔════╝██╔════╝██╔════╝    ████╗  ██║██║   ██║████╗ ████║██╔══██╗██╔════╝██╔══██╗
██║  ███╗██║   ██║█████╗  ███████╗███████╗    ██╔██╗ ██║██║   ██║██╔████╔██║██████╔╝█████╗  ██████╔╝
██║   ██║██║   ██║██╔══╝  ╚════██║╚════██║    ██║╚██╗██║██║   ██║██║╚██╔╝██║██╔══██╗██╔══╝  ██╔══██╗
╚██████╔╝╚██████╔╝███████╗███████║███████║    ██║ ╚████║╚██████╔╝██║ ╚═╝ ██║██████╔╝███████╗██║  ██║
 ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝    ╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝╚═════╝ ╚══════╝╚═╝  ╚═╝
                                                                                                    
"""

number= randint(1,100)
# print(number)
def level():
    print(game)
    welcome= "Welcome To The Game of GUESS NUMBER!"
    select="Select a Difficulty Level:"
    print(select)
    text_speech.say(welcome)
    text_speech.runAndWait()

    level_ = int(input("1. Easy (10 Chances)\n2. Medium (7 Chances)\n3. Difficult (5 Chances)\n"))
    if level_ == 1:
        chance= 10
    elif level_ == 2:
        chance= 7
    elif level_ == 3:
        chance= 5
    return chance

def get_user_guess():
    while True:
        try:
            user_guess = int(input("Guess a number (1-100): "))
            if 1 <= user_guess <= 100:
                return user_guess
            else:
                print("Please enter a number within the specified range (1-100).")
        except ValueError:
            print("Invalid input. Please enter a valid number.")

def play(chance):
    guess= get_user_guess()
    if number == guess:
        greet= "Hurray! You Guessed it Correct. Thank-You"
        print(greet)
        text_speech.say(greet)
        text_speech.runAndWait()

    elif number > guess:
        if ((number - guess) > 30):
            print("The Number Guessed is TOO LOW!")
        else:
            print("The Number Guessed is LOW!")
    elif guess > number:
        if ((guess - number) > 30):
            print("The Number Guessed is TOO HIGH!")
        else:
            print("The Number Guessed is HIGH!")
    
    if number != guess:
        chance -= 1
        if chance > 0:
            text= f"You have {chance} Chances left."
            print(text)
            text_speech.say(text)
            text_speech.runAndWait()
            play(chance)
        else:
            text= f"The CORRECT guess was {number}"
            print(text)
            end= "You Lose. Better Luck Next Time."
            print(end)
            text_speech.say(text)
            text_speech.say(end)
            text_speech.runAndWait()    
play(level())

##################################===REFENENCES===############################################
'''http://www.patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20'''
'''https://pypi.org/project/pyttsx3/'''
'''https://docs.python.org/3/library/random.html'''
